version = 0.1

[default.deploy.parameters]
stack_name = "sam-expense-google-sheets"
resolve_s3 = true
s3_prefix = "sam-expense-google-sheets"
profile = "devuser"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
