AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple API to inser values on Google Sheet expense
Globals:
  Function:
    Timeout: 15
    MemorySize: 256
  
Resources:
  UpdateGoogleSheet:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::701843240970:role/role-prod-lambda
      FunctionName: UpdateGoogleSheet
      Description: A Lambda function that updates a Google Sheet of my expenses
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      EphemeralStorage:
        Size: 512
        
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST